# -*- coding: utf-8 -*-
"""Book_Segmentation.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14__3Eo-OKyd5wICqqTvivVBQnTFNmrU2

# Augmentation — YOLOv8s-seg Training

Train a YOLOv8-small segmentation model to detect `page_left` and `page_right` in scanned document images.

**Augmentation strategy:** Only 0° and 90° rotations — fewer images, every label perfectly correct  
**Dataset:** 126 images (63 originals × 2 rotations)  
**Split:** ~88 train / ~18 val / ~20 test (seed 42, no data leakage)  
**Classes:** 0=page_left, 1=page_right  
**Model:** YOLOv8s-seg

## 1. Setup & Install
"""

!pip install ultralytics --quiet
!pip install Pillow --quiet

import ultralytics
ultralytics.checks()

"""## 2. Mount Google Drive & Extract Dataset

**Before running this cell:**
1. Zip your entire `Augmentation 2` folder
2. Upload the zip to your Google Drive
3. Update the `ZIP_PATH` below to match
"""

from google.colab import drive
drive.mount('/content/drive')

import os
import zipfile
import shutil

# ── UPDATE THIS PATH to your zip location on Google Drive ──
ZIP_PATH = '/content/drive/MyDrive/augmentation_2.zip'

WORK_DIR = '/content/dataset'

# Clean previous runs
if os.path.exists(WORK_DIR):
    shutil.rmtree(WORK_DIR)

os.makedirs(WORK_DIR, exist_ok=True)

print(f'Extracting {ZIP_PATH} ...')
with zipfile.ZipFile(ZIP_PATH, 'r') as z:
    z.extractall(WORK_DIR)

# Auto-detect if there's a nested folder
contents = os.listdir(WORK_DIR)
if len(contents) == 1 and os.path.isdir(os.path.join(WORK_DIR, contents[0])):
    DATASET_DIR = os.path.join(WORK_DIR, contents[0])
else:
    DATASET_DIR = WORK_DIR

print(f'Dataset directory: {DATASET_DIR}')
print(f'Contents: {os.listdir(DATASET_DIR)}')

"""## 3. Verify Dataset Structure"""

from pathlib import Path

ds = Path(DATASET_DIR)

for split in ['train', 'val', 'test']:
    img_dir = ds / 'images' / split
    lbl_dir = ds / 'labels' / split
    n_img = len(list(img_dir.glob('*'))) if img_dir.exists() else 0
    n_lbl = len(list(lbl_dir.glob('*.txt'))) if lbl_dir.exists() else 0
    print(f'{split:5s}: {n_img} images, {n_lbl} labels')

# Show a sample label
sample = next((ds / 'labels' / 'train').glob('*.txt'))
print(f'\nSample label ({sample.name}):')
print(sample.read_text().strip())

"""## 4. Fix data.yaml Paths for Colab"""

import yaml

data_yaml_path = os.path.join(DATASET_DIR, 'data.yaml')

data_cfg = {
    'path': DATASET_DIR,
    'train': 'images/train',
    'val': 'images/val',
    'test': 'images/test',
    'names': {
        0: 'page_left',
        1: 'page_right',
    }
}

with open(data_yaml_path, 'w') as f:
    yaml.dump(data_cfg, f, default_flow_style=False)

print('data.yaml written:')
print(open(data_yaml_path).read())

"""## 5. Convert TIFF → PNG"""

from PIL import Image
from pathlib import Path

converted = 0
for split in ['train', 'val', 'test']:
    img_dir = Path(DATASET_DIR) / 'images' / split
    if not img_dir.exists():
        continue
    for tif_path in list(img_dir.glob('*.tif')) + list(img_dir.glob('*.tiff')):
        png_path = tif_path.with_suffix('.png')
        if not png_path.exists():
            img = Image.open(tif_path)
            img.save(png_path)
            img.close()
            tif_path.unlink()
            converted += 1

print(f'Converted {converted} TIFF files to PNG')

"""## 6. Train YOLOv8s-seg

**Augmentation 2:** 126 images (2 rotations only)  
- `imgsz`: 2048 (preserves fine page boundaries)
- `epochs`: 200 (smaller dataset → more epochs, early stopping catches overfitting)
- `patience`: 40 (more patience for smaller dataset)
- `batch`: 8 (A100 40GB)
- Stronger online augmentation to compensate for smaller dataset
"""

from ultralytics import YOLO

model = YOLO('yolov8s-seg.pt')

results = model.train(
    data=data_yaml_path,
    epochs=200,
    imgsz=2048,
    batch=8,
    patience=40,
    device=0,
    workers=4,
    project='/content/runs',
    name='aug2_2rot_seg',
    exist_ok=True,
    # Stronger augmentation to compensate for smaller dataset
    augment=True,
    mosaic=1.0,
    flipud=0.5,
    fliplr=0.5,
    degrees=10.0,
    scale=0.4,
    translate=0.2,
    # Regularization
    dropout=0.15,
    weight_decay=0.001,
    # Logging
    plots=True,
    save=True,
    save_period=25,
)

"""## 7. Training Results"""

from IPython.display import Image as IPImage, display

run_dir = '/content/runs/aug2_2rot_seg'

results_img = os.path.join(run_dir, 'results.png')
if os.path.exists(results_img):
    display(IPImage(filename=results_img, width=900))

cm_img = os.path.join(run_dir, 'confusion_matrix_normalized.png')
if os.path.exists(cm_img):
    display(IPImage(filename=cm_img, width=600))

"""## 8. Validate on Val Set"""

best_model = YOLO(os.path.join(run_dir, 'weights', 'best.pt'))

val_results = best_model.val(
    data=data_yaml_path,
    split='val',
    imgsz=2048,
    batch=8,
    device=0,
    plots=True,
)

print(f"\nmAP50     (mask): {val_results.seg.map50:.4f}")
print(f"mAP50-95  (mask): {val_results.seg.map:.4f}")
print(f"mAP50     (box):  {val_results.box.map50:.4f}")
print(f"mAP50-95  (box):  {val_results.box.map:.4f}")

"""## 9. Evaluate on Test Set"""

test_results = best_model.val(
    data=data_yaml_path,
    split='test',
    imgsz=2048,
    batch=8,
    device=0,
    plots=True,
)

print(f"\nTest mAP50     (mask): {test_results.seg.map50:.4f}")
print(f"Test mAP50-95  (mask): {test_results.seg.map:.4f}")
print(f"Test mAP50     (box):  {test_results.box.map50:.4f}")
print(f"Test mAP50-95  (box):  {test_results.box.map:.4f}")

"""## 10. Inference Demo with Post-Processing"""

import numpy as np
from dataclasses import dataclass, field
from typing import List, Tuple

CONFIDENCE_THRESHOLD = 0.50

@dataclass
class PageDetection:
    class_id: int
    confidence: float
    polygon: np.ndarray

    @property
    def centroid(self) -> Tuple[float, float]:
        return float(self.polygon[:, 0].mean()), float(self.polygon[:, 1].mean())


@dataclass
class PostProcessResult:
    detections: List[PageDetection]
    page_count: int
    split_required: bool
    layout: str = 'unknown'
    needs_review: bool = False
    warnings: List[str] = field(default_factory=list)


def classify_layout(det_a, det_b):
    cx_a, cy_a = det_a.centroid
    cx_b, cy_b = det_b.centroid
    dx, dy = abs(cx_a - cx_b), abs(cy_a - cy_b)
    if dx < 1e-6 and dy < 1e-6:
        return 'ambiguous'
    return 'horizontal' if dx >= dy else 'vertical'


def validate_page_assignments(detections):
    warnings = []
    needs_review = False

    if len(detections) == 0:
        return PostProcessResult([], 0, False, layout='empty', needs_review=True,
                                 warnings=['No pages detected.'])
    if len(detections) == 1:
        det = detections[0]
        nr = det.confidence < CONFIDENCE_THRESHOLD
        w = [f'Low confidence ({det.confidence:.2f}).'] if nr else []
        return PostProcessResult(detections, 1, False, layout='single', needs_review=nr, warnings=w)
    if len(detections) > 2:
        warnings.append(f'Expected 1-2 pages, got {len(detections)}. Using top 2.')
        detections = sorted(detections, key=lambda d: d.confidence, reverse=True)[:2]

    det_a, det_b = detections
    layout = classify_layout(det_a, det_b)

    classes = {det_a.class_id, det_b.class_id}
    if classes != {0, 1}:
        needs_review = True
        warnings.append(f'Duplicate classes: both are class {det_a.class_id}. Needs review.')

    min_conf = min(det_a.confidence, det_b.confidence)
    if min_conf < CONFIDENCE_THRESHOLD:
        needs_review = True
        warnings.append(f'Low confidence ({min_conf:.2f}). Needs review.')

    ordered = sorted(detections, key=lambda d: d.class_id)
    return PostProcessResult(ordered, 2, True, layout, needs_review, warnings)


def parse_yolo_seg_results(results, conf_threshold=0.25):
    detections = []
    if results.masks is None:
        return detections
    for mask_xy, box in zip(results.masks.xyn, results.boxes):
        conf = float(box.conf[0])
        if conf < conf_threshold:
            continue
        detections.append(PageDetection(
            class_id=int(box.cls[0]),
            confidence=conf,
            polygon=np.array(mask_xy),
        ))
    return detections

print('Post-processing loaded.')

import matplotlib.pyplot as plt
from PIL import Image

CLASS_NAMES = {0: 'page_left', 1: 'page_right'}
CLASS_COLORS = {0: 'blue', 1: 'red'}

test_images = sorted(Path(DATASET_DIR, 'images', 'test').glob('*.png'))[:6]

fig, axes = plt.subplots(2, 3, figsize=(18, 12))
axes = axes.flatten()

for ax, img_path in zip(axes, test_images):
    results = best_model(str(img_path), imgsz=2048, verbose=False)[0]
    dets = parse_yolo_seg_results(results)
    pp = validate_page_assignments(dets)

    img = Image.open(img_path)
    w, h = img.size
    ax.imshow(img)

    for det in pp.detections:
        poly = det.polygon * np.array([w, h])
        poly_closed = np.vstack([poly, poly[0]])
        color = CLASS_COLORS[det.class_id]
        ax.plot(poly_closed[:, 0], poly_closed[:, 1], '-', color=color, linewidth=2)
        cx, cy = det.centroid
        ax.text(cx * w, cy * h, f"{CLASS_NAMES[det.class_id]}\n{det.confidence:.2f}",
                color='white', fontsize=9, ha='center', va='center',
                bbox=dict(boxstyle='round,pad=0.3', facecolor=color, alpha=0.7))

    title = img_path.stem[:30]
    if pp.needs_review:
        title += ' ⚠ REVIEW'
    ax.set_title(title, fontsize=10)
    ax.axis('off')

plt.tight_layout()
plt.savefig(os.path.join(run_dir, 'test_inference_demo.png'), dpi=150)
plt.show()

"""## 11. Export Model"""

import shutil

SAVE_DIR = '/content/drive/MyDrive/libraryai_models'
os.makedirs(SAVE_DIR, exist_ok=True)

best_pt = os.path.join(run_dir, 'weights', 'best.pt')
last_pt = os.path.join(run_dir, 'weights', 'last.pt')

shutil.copy2(best_pt, os.path.join(SAVE_DIR, 'aug2_2rot_best.pt'))
shutil.copy2(last_pt, os.path.join(SAVE_DIR, 'aug2_2rot_last.pt'))

results_png = os.path.join(run_dir, 'results.png')
if os.path.exists(results_png):
    shutil.copy2(results_png, os.path.join(SAVE_DIR, 'aug2_2rot_results.png'))

print(f'Model saved to {SAVE_DIR}/')
print(f'  best.pt: {os.path.getsize(best_pt) / 1e6:.1f} MB')

"""## 12. Full Inference Pipeline Function"""

def predict_pages(model, image_path, imgsz=2048, conf=0.25):
    results = model(str(image_path), imgsz=imgsz, device=0, verbose=False)[0]
    detections = parse_yolo_seg_results(results, conf_threshold=conf)
    return validate_page_assignments(detections)


if test_images:
    result = predict_pages(best_model, test_images[0])
    print(f'Image: {test_images[0].name}')
    print(f'Pages: {result.page_count}, Split: {result.split_required}')
    print(f'Layout: {result.layout}, Review: {result.needs_review}')
    for d in result.detections:
        print(f'  {CLASS_NAMES[d.class_id]}: conf={d.confidence:.3f}, centroid={d.centroid}')
    if result.warnings:
        print(f'Warnings: {result.warnings}')