# -*- coding: utf-8 -*-
"""Microfilm_Segmentation.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fAfeRmkaYzjfFNgb7qn67cMJ_5xdx5g1

# IEP1A — YOLOv8-seg Training
**Page segmentation model for microfilm data**

Prerequisites:
1. Upload `merged_dataset.zip` to Google Drive root (`My Drive/`)
2. Set runtime to **GPU** (Runtime → Change runtime type → T4 GPU)
3. Run all cells
"""

!pip install -q ultralytics

from google.colab import drive
drive.mount('/content/drive')

# Assuming 'merged_dataset' is already an unzipped directory in MyDrive.
# If it's still a zip file, you would need to unzip it.
!ls /content/drive/MyDrive/merged_dataset/images/

# Fix data.yaml path for Colab to point to Google Drive
from pathlib import Path

data_yaml_path = Path("/content/drive/MyDrive/merged_dataset/data.yaml")
text = data_yaml_path.read_text()

# Replace the local path with the Google Drive path
lines = []
for line in text.splitlines():
    if line.startswith("path:"):
        lines.append("path: /content/drive/MyDrive/merged_dataset")
    else:
        lines.append(line)
data_yaml_path.write_text("\n".join(lines) + "\n")

print(data_yaml_path.read_text())

# Quick sanity check — count files, now pointing to Google Drive
for split in ['train', 'val', 'test']:
    imgs = list(Path(f'/content/drive/MyDrive/merged_dataset/images/{split}').glob('*'))
    lbls = list(Path(f'/content/drive/MyDrive/merged_dataset/labels/{split}').glob('*'))
    print(f'{split:5s}: {len(imgs)} images, {len(lbls)} labels')

"""Display visualize"""

import glob
import random
from IPython.display import display, Image as IPImage
from pathlib import Path
from PIL import Image, ImageDraw # Import ImageDraw for drawing on images
import io

# Get all training images
train_images_path = '/content/drive/MyDrive/merged_dataset/images/train/'
train_labels_path = '/content/drive/MyDrive/merged_dataset/labels/train/'

all_train_images = list(Path(train_images_path).glob('*.tif'))

# Select 10 random images
if len(all_train_images) > 10:
    sample_images = random.sample(all_train_images, 10)
else:
    sample_images = all_train_images

print(f"Displaying {len(sample_images)} random samples from the training set with segmentation labels:")

for img_path in sample_images:
    try:
        # Open the TIFF image with Pillow
        img = Image.open(img_path).convert("RGB") # Ensure image is in RGB format for drawing
        draw = ImageDraw.Draw(img)

        # Try to find and draw the corresponding label file
        label_name = img_path.stem + '.txt'
        label_path = Path(train_labels_path) / label_name

        if label_path.exists():
            with open(label_path, 'r') as f:
                for line in f.readlines():
                    parts = line.strip().split()
                    class_id = int(parts[0])
                    # Coordinates are normalized, so scale them back
                    polygon_coords = []
                    for i in range(1, len(parts), 2):
                        x = float(parts[i]) * img.width
                        y = float(parts[i+1]) * img.height
                        polygon_coords.append((x, y))

                    # Draw the polygon outline (e.g., in red, with a line width)
                    draw.polygon(polygon_coords, outline=(255, 0, 0), width=3) # Red outline
                    # You could also fill it with transparency if desired
                    # draw.polygon(polygon_coords, fill=(255, 0, 0, 50)) # Red with 50 alpha

        # Convert the modified image to PNG and save to a byte stream
        with io.BytesIO() as output:
            img.save(output, format="PNG")
            # Display the PNG image from the byte stream
            display(IPImage(data=output.getvalue(), width=400))

        # Print the label text for reference (optional, but good for verification)
        if label_path.exists():
            print(f"Label for {img_path.name}:")
            with open(label_path, 'r') as f:
                for line in f.readlines():
                    print(line.strip())
        else:
            print(f"No label found for {img_path.name}")

    except Exception as e:
        print(f"Could not display or process {img_path.name}: {e}")

    print("\n" + "-"*50 + "\n")

"""Train

## Convert TIFF images to RGB JPG for training
"""

import os
from pathlib import Path
from PIL import Image
import shutil

original_dataset_path = Path('/content/drive/MyDrive/merged_dataset')
temp_dataset_path = Path('/content/temp_yolov8_dataset')

# Remove existing temp dataset if it exists
if temp_dataset_path.exists():
    shutil.rmtree(temp_dataset_path)

# Create the new temporary dataset structure
temp_dataset_path.mkdir(parents=True, exist_ok=True)
(temp_dataset_path / 'images' / 'train').mkdir(parents=True, exist_ok=True)
(temp_dataset_path / 'images' / 'val').mkdir(parents=True, exist_ok=True)
(temp_dataset_path / 'images' / 'test').mkdir(parents=True, exist_ok=True)
(temp_dataset_path / 'labels' / 'train').mkdir(parents=True, exist_ok=True)
(temp_dataset_path / 'labels' / 'val').mkdir(parents=True, exist_ok=True)
(temp_dataset_path / 'labels' / 'test').mkdir(parents=True, exist_ok=True)

print(f"Created temporary dataset structure at {temp_dataset_path}")

# Copy label files and convert image files
for split in ['train', 'val', 'test']:
    original_images_split_path = original_dataset_path / 'images' / split
    original_labels_split_path = original_dataset_path / 'labels' / split
    temp_images_split_path = temp_dataset_path / 'images' / split
    temp_labels_split_path = temp_dataset_path / 'labels' / split

    # Copy all label files
    for label_file in original_labels_split_path.glob('*.txt'):
        shutil.copy(label_file, temp_labels_split_path / label_file.name)

    # Convert and copy image files
    for img_file in original_images_split_path.glob('*.tif'):
        try:
            img = Image.open(img_file).convert('RGB') # Convert to RGB
            new_img_name = img_file.stem + '.jpg' # Change extension to jpg
            img.save(temp_images_split_path / new_img_name, quality=90) # Save as JPG
        except Exception as e:
            print(f"Error processing {img_file.name}: {e}")

print("Labels copied and TIFF images converted to JPG (RGB) in temporary dataset.")

# Update data.yaml for the temporary dataset
data_yaml_content = f"""
path: {temp_dataset_path}
train: images/train
val: images/val
test: images/test

names:
  0: page_left
  1: page_right
"""
(temp_dataset_path / 'data.yaml').write_text(data_yaml_content.strip())
print(f"New data.yaml created at {temp_dataset_path / 'data.yaml'}")

"""Now, we will modify the training cell to use this newly created temporary dataset and its `data.yaml`."""

from ultralytics import YOLO

# Choose model size:
#   yolov8n-seg.pt  — nano  (fastest, least accurate)
#   yolov8s-seg.pt  — small (good balance)
#   yolov8m-seg.pt  — medium (best accuracy, slower)
model = YOLO('yolov8n-seg.pt')

results = model.train(
    data='/content/temp_yolov8_dataset/data.yaml', # UPDATED path to temporary converted dataset
    epochs=100,
    imgsz=640,
    batch=16,
    patience=20,
    project='/content/runs',
    name='iep1a_seg',
    exist_ok=True,
    device=0,
    workers=2,
    # augmentation
    flipud=0.0,
    fliplr=0.5,
    mosaic=1.0,
    mixup=0.1,
    degrees=5.0,
    translate=0.1,
    scale=0.3,
    shear=2.0,
)

metrics = model.val(
    data='/content/temp_yolov8_dataset/data.yaml', # UPDATED path to temporary converted dataset
    split='test',
)
print(f'Test mAP50:    {metrics.seg.map50:.4f}')
print(f'Test mAP50-95: {metrics.seg.map:.4f}')

import glob
from IPython.display import display, Image as IPImage

# UPDATED path to temporary converted dataset images
test_images = sorted(glob.glob('/content/temp_yolov8_dataset/images/test/*.jpg'))[:6]
preds = model.predict(test_images, imgsz=640, conf=0.5, save=True,
                      project='/content/runs', name='test_preds', exist_ok=True)

# Show saved prediction images
for img_path in sorted(glob.glob('/content/runs/test_preds/*.jpg'))[:6]: # Expecting JPG outputs
    display(IPImage(filename=img_path, width=500))

"""## Visualize Data Samples

## Evaluate on Test Set
"""

metrics = model.val(
    data='/content/temp_yolov8_dataset/data.yaml', # UPDATED path to temporary converted dataset
    split='test',
)
print(f'Test mAP50:    {metrics.seg.map50:.4f}')
print(f'Test mAP50-95: {metrics.seg.map:.4f}')

"""## Visualize Predictions on Test Images"""

import glob
from IPython.display import display, Image as IPImage

# Get all test images from the temporary converted dataset
all_test_images = sorted(glob.glob('/content/temp_yolov8_dataset/images/test/*.jpg'))

# Select samples from the beginning, middle, and end of the list
num_samples = len(all_test_images)
selected_indices = set()

if num_samples >= 6:
    # Take 2 from beginning
    selected_indices.add(0)
    selected_indices.add(1)
    # Take 2 from middle
    selected_indices.add(num_samples // 2 - 1)
    selected_indices.add(num_samples // 2)
    # Take 2 from end
    selected_indices.add(num_samples - 2)
    selected_indices.add(num_samples - 1)
elif num_samples > 0:
    # If less than 6, take all available
    selected_indices = set(range(num_samples))

# Sort the selected indices to ensure ordered display
sorted_selected_indices = sorted(list(selected_indices))
test_images_to_predict = [all_test_images[i] for i in sorted_selected_indices]

print(f"Predicting on {len(test_images_to_predict)} selected test images...")
preds = model.predict(test_images_to_predict, imgsz=640, conf=0.5, save=True,
                      project='/content/runs', name='test_preds_expanded', exist_ok=True)

# Show saved prediction images
print("Displaying predictions:")
for img_path in sorted(glob.glob('/content/runs/test_preds_expanded/*.jpg')):
    display(IPImage(filename=img_path, width=500))

"""## Save Best Weights to Google Drive"""

import shutil

src = '/content/runs/iep1a_seg/weights/best.pt'
dst = '/content/drive/MyDrive/iep1a_best.pt'
shutil.copy(src, dst)
print(f'Best weights saved to Google Drive: {dst}')