# -*- coding: utf-8 -*-
"""Newspapers_segmentation.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gzPA9HUW8Wp-ZfVfIgQ4Wj7xMyzQgHmA
"""

!pip -q install ultralytics

from google.colab import drive
drive.mount('/content/drive')

DATA_DIR = "/content/drive/MyDrive/augmentation2_code"

from pathlib import Path

data_dir = Path(DATA_DIR)
exts = {".tif", ".tiff", ".jpg", ".jpeg", ".png"}

for split in ["train", "val", "test"]:
    img_dir = data_dir / "images" / split
    files = sorted([p for p in img_dir.iterdir() if p.suffix.lower() in exts])
    (data_dir / f"{split}.txt").write_text("\n".join(str(p) for p in files) + ("\n" if files else ""))

print("Rebuilt train/val/test txt files.")

yaml_text = f"""path: {DATA_DIR}
train: train.txt
val: val.txt
test: test.txt
names:
  0: page_left
  1: page_right
"""
with open("/content/aug2_data.yaml", "w") as f:
    f.write(yaml_text)

print("Wrote /content/aug2_data.yaml")

from pathlib import Path
from PIL import Image

DATA_DIR = Path("/content/drive/MyDrive/augmentation2_code")
exts = {".tif", ".tiff", ".jpg", ".jpeg", ".png"}

converted = 0
for split in ["train", "val", "test"]:
    for p in (DATA_DIR / "images" / split).iterdir():
        if p.suffix.lower() not in exts:
            continue
        with Image.open(p) as im:
            if im.mode != "RGB":
                im.convert("RGB").save(p)
                converted += 1

print("Converted to RGB:", converted)

!yolo task=segment mode=train \
  model=yolov8s-seg.pt \
  data=/content/aug2_data.yaml \
  imgsz=640 batch=8 epochs=50 device=0 \
  name=aug2_yolov8s

!yolo task=segment mode=val \
  model=/content/runs/segment/aug2_yolov8s/weights/best.pt \
  data=/content/aug2_data.yaml \
  split=test device=0

!yolo task=segment mode=predict \
  model=/content/runs/segment/aug2_yolov8s/weights/best.pt \
  source=/content/drive/MyDrive/imagee.png \
  conf=0.25 save=True device=0