# -*- coding: utf-8 -*-
"""Book_Keypoints.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wLDJ-fnigUjC7OXpP-XqbWmQYy5M4y-_

# IEP1B — YOLOv8-Pose Keypoint Training (Book Page Corners)

This notebook:
1. Mounts Google Drive
2. Splits data into train/val/test (70/15/15 by original image, keeping augmentations with their originals)
3. Builds the YOLO directory structure
4. Trains YOLOv8-pose
5. Evaluates on val and test sets

**Classes:** `page_left` (0), `page_right` (1)  
**Keypoints:** 4 per detection (TL, TR, BR, BL)  
**Images:** TIFF scans from AUB collections

## 0. Setup
"""

# Mount Google Drive
from google.colab import drive
drive.mount('/content/drive')

# Install ultralytics
!pip install -q ultralytics

import os
import shutil
import random
import yaml
from pathlib import Path
from collections import defaultdict

# ============================================================
# CONFIGURE THIS: path to your uploaded dataset on Google Drive
# ============================================================
DRIVE_DATA = Path("/content/drive/MyDrive/book keypoints")  # <-- CHANGE THIS to your actual Drive path

# Working directory on the Colab local disk (faster I/O)
WORK_DIR = Path("/content/keypoint_dataset")

# Split fractions (must sum to 1.0)
TRAIN_FRACTION = 0.70
VAL_FRACTION = 0.15
TEST_FRACTION = 0.15

# Random seed for reproducibility
SEED = 42

# Image extensions to look for
IMAGE_EXTS = {".tif", ".tiff", ".png", ".jpg", ".jpeg"}

print(f"Drive data path: {DRIVE_DATA}")
print(f"Working directory: {WORK_DIR}")
print(f"Split: {TRAIN_FRACTION:.0%} train / {VAL_FRACTION:.0%} val / {TEST_FRACTION:.0%} test")

"""## 1. Copy Data from Drive to Local Disk

Training is much faster when reading from Colab's local SSD rather than Drive.
"""

# Verify source exists
src_images = DRIVE_DATA / "images" / "train"
src_labels = DRIVE_DATA / "labels" / "train"

assert src_images.exists(), f"Images folder not found: {src_images}"
assert src_labels.exists(), f"Labels folder not found: {src_labels}"

img_files = sorted([f for f in src_images.iterdir() if f.suffix.lower() in IMAGE_EXTS])
lbl_files = sorted(src_labels.glob("*.txt"))

print(f"Found {len(img_files)} images and {len(lbl_files)} label files on Drive")

"""## 2. Split into Train / Val / Test

**Critical:** We split by *original* image stem, then assign all augmented variants (e.g. `_rot90`) to the same split. This prevents data leakage.
"""

# Group label files: original stem -> [original, augmented variants]
# Augmented files end with _rot90, _rot180, _rot270
import re

def get_original_stem(filename_stem):
    """Strip rotation suffix to get the original image stem."""
    return re.sub(r'_rot(90|180|270)$', '', filename_stem)

# Build mapping: original_stem -> list of label file stems (including augmented)
groups = defaultdict(list)
for lbl in lbl_files:
    orig = get_original_stem(lbl.stem)
    groups[orig].append(lbl.stem)

original_stems = sorted(groups.keys())
print(f"Found {len(original_stems)} original images ({sum(len(v) for v in groups.values())} total with augmentations)")

# Shuffle and split into train / val / test
random.seed(SEED)
shuffled = original_stems.copy()
random.shuffle(shuffled)

n_test = max(1, int(len(shuffled) * TEST_FRACTION))
n_val = max(1, int(len(shuffled) * VAL_FRACTION))
# Remainder goes to train

test_originals = set(shuffled[:n_test])
val_originals = set(shuffled[n_test:n_test + n_val])
train_originals = set(shuffled[n_test + n_val:])

print(f"\nSplit (by original image):")
print(f"  Train: {len(train_originals)}")
print(f"  Val:   {len(val_originals)}")
print(f"  Test:  {len(test_originals)}")

# Expand to include augmented variants
train_stems = set()
val_stems = set()
test_stems = set()
for orig in train_originals:
    train_stems.update(groups[orig])
for orig in val_originals:
    val_stems.update(groups[orig])
for orig in test_originals:
    test_stems.update(groups[orig])

print(f"\nTotal files (with augmentations):")
print(f"  Train: {len(train_stems)}")
print(f"  Val:   {len(val_stems)}")
print(f"  Test:  {len(test_stems)}")

"""## 3. Build YOLO Directory Structure"""

# Create directory structure
for split in ["train", "val", "test"]:
    (WORK_DIR / "images" / split).mkdir(parents=True, exist_ok=True)
    (WORK_DIR / "labels" / split).mkdir(parents=True, exist_ok=True)

def find_image_for_stem(stem, src_dir):
    """Find the image file matching a given stem."""
    for ext in IMAGE_EXTS:
        candidate = src_dir / f"{stem}{ext}"
        if candidate.exists():
            return candidate
    return None

def copy_pair(stem, split):
    """Copy image + label for a given stem into the split folder."""
    # Label
    lbl_src = src_labels / f"{stem}.txt"
    if lbl_src.exists():
        shutil.copy2(lbl_src, WORK_DIR / "labels" / split / f"{stem}.txt")

    # Image
    img_src = find_image_for_stem(stem, src_images)
    if img_src:
        shutil.copy2(img_src, WORK_DIR / "images" / split / img_src.name)
    else:
        print(f"  WARNING: No image found for {stem}")

# Copy files
for split_name, stems in [("train", train_stems), ("val", val_stems), ("test", test_stems)]:
    print(f"Copying {split_name} files...")
    for stem in sorted(stems):
        copy_pair(stem, split_name)

# Verify counts
for split in ["train", "val", "test"]:
    n_img = len(list((WORK_DIR / "images" / split).iterdir()))
    n_lbl = len(list((WORK_DIR / "labels" / split).iterdir()))
    print(f"  {split:5s}: {n_img} images, {n_lbl} labels")

"""## 4. Write `data.yaml`"""

data_yaml = {
    "path": str(WORK_DIR),
    "train": "images/train",
    "val": "images/val",
    "test": "images/test",
    "names": {
        0: "page_left",
        1: "page_right",
    },
    "kpt_shape": [4, 3],  # 4 keypoints, 3 values each (x, y, visibility)
}

yaml_path = WORK_DIR / "data.yaml"
with open(yaml_path, "w") as f:
    yaml.dump(data_yaml, f, default_flow_style=False)

print(f"Written: {yaml_path}")
print(open(yaml_path).read())

"""## 5. Sanity Check — Visualize a Sample"""

import matplotlib.pyplot as plt
import matplotlib.patches as patches
from PIL import Image
import numpy as np

def visualize_sample(images_dir, labels_dir, idx=0):
    """Show an image with its bounding boxes and keypoints overlaid."""
    img_files_local = sorted([f for f in Path(images_dir).iterdir() if f.suffix.lower() in IMAGE_EXTS])
    if idx >= len(img_files_local):
        print("Index out of range")
        return

    img_path = img_files_local[idx]
    lbl_path = Path(labels_dir) / f"{img_path.stem}.txt"

    img = Image.open(img_path)
    if img.mode != "RGB":
        img = img.convert("RGB")
    img_np = np.array(img)
    h, w = img_np.shape[:2]

    fig, ax = plt.subplots(1, 1, figsize=(12, 10))
    ax.imshow(img_np)
    ax.set_title(img_path.name, fontsize=10)

    if lbl_path.exists():
        for line in lbl_path.read_text().strip().splitlines():
            parts = line.split()
            cls_id = int(parts[0])
            cx, cy, bw, bh = float(parts[1]), float(parts[2]), float(parts[3]), float(parts[4])

            # Draw bounding box
            x1 = (cx - bw/2) * w
            y1 = (cy - bh/2) * h
            rect = patches.Rectangle((x1, y1), bw * w, bh * h,
                                     linewidth=2, edgecolor='lime', facecolor='none')
            ax.add_patch(rect)
            ax.text(x1, y1 - 5, f"{'page_left' if cls_id == 0 else 'page_right'}",
                    color='lime', fontsize=9, weight='bold')

            # Draw keypoints (TL, TR, BR, BL)
            kp_names = ["TL", "TR", "BR", "BL"]
            kp_colors = ["red", "blue", "yellow", "cyan"]
            for i in range(4):
                base = 5 + i * 3
                kx, ky, kv = float(parts[base]), float(parts[base+1]), int(parts[base+2])
                if kv > 0:
                    ax.plot(kx * w, ky * h, 'o', color=kp_colors[i], markersize=8)
                    ax.text(kx * w + 5, ky * h - 5, kp_names[i],
                            color=kp_colors[i], fontsize=8, weight='bold')

    ax.axis('off')
    plt.tight_layout()
    plt.show()

# Show first train sample
visualize_sample(WORK_DIR / "images" / "train", WORK_DIR / "labels" / "train", idx=0)

"""## 6. Train YOLOv8-Pose

**Per spec:** use `imgsz=2048` for production quality. Use `imgsz=1024` for quick prototyping.

Adjust `epochs` and `batch` based on your GPU (Colab free tier → T4 16GB, reduce batch if OOM).
"""

from ultralytics import YOLO

# ============================================================
# TRAINING CONFIGURATION
# ============================================================
MODEL_SIZE = "m"            # n, s, m, l, x  (start with 'm' for a good balance)
IMGSZ = 1024                # 2048 for production, 1024 for prototyping
EPOCHS = 100                # Increase for production (200-300)
BATCH = 4                   # Reduce to 2 if OOM on T4, increase on A100
PATIENCE = 20               # Early stopping patience

# Output directory for runs (saved to Drive so you don't lose results)
RUN_PROJECT = "/content/drive/MyDrive/yolo_runs/iep1b_keypoints"
RUN_NAME = f"pose_{MODEL_SIZE}_imgsz{IMGSZ}_e{EPOCHS}"

print(f"Model: yolov8{MODEL_SIZE}-pose")
print(f"Image size: {IMGSZ}")
print(f"Epochs: {EPOCHS}")
print(f"Batch: {BATCH}")
print(f"Output: {RUN_PROJECT}/{RUN_NAME}")

# Load pretrained YOLOv8-pose model
model = YOLO(f"yolov8{MODEL_SIZE}-pose.pt")

# Train
results = model.train(
    data=str(yaml_path),
    epochs=EPOCHS,
    imgsz=IMGSZ,
    batch=BATCH,
    patience=PATIENCE,
    project=RUN_PROJECT,
    name=RUN_NAME,
    exist_ok=True,
    # Augmentation (reasonable defaults for document images)
    hsv_h=0.01,        # Minimal hue shift (documents)
    hsv_s=0.3,
    hsv_v=0.3,
    degrees=5.0,       # Small rotation (you already have rot90 augmentation)
    translate=0.05,
    scale=0.15,
    flipud=0.0,        # No vertical flip (pages don't appear upside-down normally)
    fliplr=0.0,        # No horizontal flip (would swap left/right semantics)
    mosaic=0.0,        # Disable mosaic (bad for full-page detection)
    mixup=0.0,         # Disable mixup
    copy_paste=0.0,    # Disable copy-paste
    # Optimizer
    optimizer="AdamW",
    lr0=0.001,
    lrf=0.01,
    weight_decay=0.0005,
    warmup_epochs=5,
    # Misc
    workers=2,
    device=0,          # GPU
    verbose=True,
)

"""## 7. Evaluate on Validation and Test Sets"""

# Validate best model
best_model_path = Path(RUN_PROJECT) / RUN_NAME / "weights" / "best.pt"
print(f"Best model: {best_model_path}")

model_best = YOLO(str(best_model_path))

# --- Validation set ---
print("\n=== VALIDATION SET ===")
metrics_val = model_best.val(
    data=str(yaml_path),
    imgsz=IMGSZ,
    batch=BATCH,
    device=0,
)
print(f"  Box  mAP50:    {metrics_val.box.map50:.4f}")
print(f"  Box  mAP50-95: {metrics_val.box.map:.4f}")
print(f"  Pose mAP50:    {metrics_val.pose.map50:.4f}")
print(f"  Pose mAP50-95: {metrics_val.pose.map:.4f}")

# --- Test set ---
print("\n=== TEST SET ===")
metrics_test = model_best.val(
    data=str(yaml_path),
    split="test",
    imgsz=IMGSZ,
    batch=BATCH,
    device=0,
)
print(f"  Box  mAP50:    {metrics_test.box.map50:.4f}")
print(f"  Box  mAP50-95: {metrics_test.box.map:.4f}")
print(f"  Pose mAP50:    {metrics_test.pose.map50:.4f}")
print(f"  Pose mAP50-95: {metrics_test.pose.map:.4f}")

"""## 8. Inference Test — Predict on Test Samples"""

# Run prediction on test images (unseen during training & validation)
test_imgs = sorted([f for f in (WORK_DIR / "images" / "test").iterdir() if f.suffix.lower() in IMAGE_EXTS])[:4]

results_pred = model_best.predict(
    source=[str(p) for p in test_imgs],
    imgsz=IMGSZ,
    conf=0.25,
    device=0,
    save=False,
)

fig, axes = plt.subplots(1, len(test_imgs), figsize=(6 * len(test_imgs), 8))
if len(test_imgs) == 1:
    axes = [axes]

for ax, result in zip(axes, results_pred):
    img_plot = result.plot()
    ax.imshow(img_plot[..., ::-1])  # BGR -> RGB
    ax.set_title(Path(result.path).name, fontsize=9)
    ax.axis('off')

plt.tight_layout()
plt.show()

"""## 9. Export Best Model"""

# Export to ONNX for deployment (optional)
model_best.export(format="onnx", imgsz=IMGSZ, simplify=True)

"""## 11. Download Best Model"""

from google.colab import files

# Path to the exported ONNX model
onnx_model_path = Path(RUN_PROJECT) / RUN_NAME / "weights" / "best.onnx"

if onnx_model_path.exists():
    print(f"Downloading {onnx_model_path.name}...")
    files.download(str(onnx_model_path))
else:
    print(f"Error: ONNX model not found at {onnx_model_path}")

"""## Download Best PyTorch Model"""

from google.colab import files
from pathlib import Path

# Construct the path to the best.pt model
best_pt_model_path = Path(RUN_PROJECT) / RUN_NAME / "weights" / "best.pt"

if best_pt_model_path.exists():
    print(f"Downloading {best_pt_model_path.name}...")
    files.download(str(best_pt_model_path))
else:
    print(f"Error: best.pt model not found at {best_pt_model_path}")

"""## 10. Copy Best Weights Back to Drive"""

# The training output is already saved to Drive (RUN_PROJECT is on Drive)
print(f"\nTraining results saved at: {RUN_PROJECT}/{RUN_NAME}")
print(f"Best weights: {best_model_path}")
print(f"\nFiles in run directory:")
for f in sorted(Path(RUN_PROJECT, RUN_NAME).rglob("*")):
    if f.is_file():
        print(f"  {f.relative_to(Path(RUN_PROJECT, RUN_NAME))}")