# -*- coding: utf-8 -*-
"""newspapers_keypoints.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mgzcBMkcRHAyKE-GOUuv7kFGKeiSaQ_H
"""

from google.colab import drive
drive.mount('/content/drive')

!pip install -q ultralytics

from pathlib import Path

DRIVE_DATA = Path("/content/drive/MyDrive/augm_keypoints")  # <-- change to match Drive

from pathlib import Path
import yaml

# Folder on Drive that contains images/ and labels/
DATA_ROOT = Path("/content/drive/MyDrive/augm_keypoints")  # <-- your path

data_yaml = {
    "path": str(DATA_ROOT),
    "train": "images/train",
    "val": "images/val",
    "test": "images/test",
    "names": {0: "page_left", 1: "page_right"},
    "kpt_shape": [4, 3],
}

yaml_path = Path("/content/iep1b_data.yaml")  # local small file
yaml_path.write_text(yaml.dump(data_yaml, default_flow_style=False))
print(yaml_path.read_text())

from ultralytics import YOLO
from pathlib import Path

MODEL_SIZE = "m"
IMGSZ = 1024
EPOCHS = 100
BATCH = 4
PATIENCE = 20

RUN_PROJECT = "/content/drive/MyDrive/yolo_runs/iep1b_keypoints"
RUN_NAME = f"pose_{MODEL_SIZE}_imgsz{IMGSZ}_e{EPOCHS}"

model = YOLO(f"yolov8{MODEL_SIZE}-pose.pt")

results = model.train(
    data=str(yaml_path),
    epochs=EPOCHS,
    imgsz=IMGSZ,
    batch=BATCH,
    patience=PATIENCE,
    project=RUN_PROJECT,
    name=RUN_NAME,
    exist_ok=True,
    hsv_h=0.01,
    hsv_s=0.3,
    hsv_v=0.3,
    degrees=5.0,
    translate=0.05,
    scale=0.15,
    flipud=0.0,
    fliplr=0.0,
    mosaic=0.0,
    mixup=0.0,
    copy_paste=0.0,
    optimizer="AdamW",
    lr0=0.001,
    lrf=0.01,
    weight_decay=0.0005,
    warmup_epochs=5,
    workers=2,
    device=0,
    verbose=True,
)

from ultralytics import YOLO

model = YOLO("/content/drive/MyDrive/yolo_runs/iep1b_keypoints/pose_m_imgsz1024_e100/weights/best.pt")

metrics_val = model.val(data="/content/iep1b_data.yaml", imgsz=1024, batch=4, device=0)
metrics_test = model.val(data="/content/iep1b_data.yaml", split="test", imgsz=1024, batch=4, device=0)

print("val  pose mAP50:", metrics_val.pose.map50)
print("test pose mAP50:", metrics_test.pose.map50)