# -*- coding: utf-8 -*-
"""classifier.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Qz1Vlz6mY9qjee1VDA_nguPEjJduXKRa
"""

from google.colab import drive
drive.mount('/content/drive')

!pip -q install ultralytics

!rm -rf /content/classifier
!cp -r "/content/drive/MyDrive/classifier" /content/classifier

from pathlib import Path
from PIL import Image

ROOT = Path("/content/drive/MyDrive/classifier")
TRAIN = ROOT / "train"
EXTS = {".jpg", ".jpeg", ".png", ".tif", ".tiff", ".bmp", ".webp"}

print("ROOT exists:", ROOT.exists())
print("TRAIN exists:", TRAIN.exists())
if not TRAIN.exists():
    raise FileNotFoundError(f"Missing: {TRAIN}")

ROTATIONS = [
    ("rot90",  Image.Transpose.ROTATE_270),  # 90 CW
    ("rot180", Image.Transpose.ROTATE_180),
    ("rot270", Image.Transpose.ROTATE_90),   # 270 CW
]

created = 0
for class_dir in TRAIN.iterdir():
    if not class_dir.is_dir():
        continue
    for p in class_dir.iterdir():
        if p.suffix.lower() not in EXTS:
            continue
        if any(tag in p.stem for tag, _ in ROTATIONS):
            continue
        with Image.open(p) as im:
            for tag, op in ROTATIONS:
                out = class_dir / f"{p.stem}_{tag}{p.suffix}"
                if not out.exists():
                    im.transpose(op).save(out)
                    created += 1

print("Created rotated images:", created)

from pathlib import Path

root = Path("/content/drive/MyDrive/classifier")  # use Drive path
for split in ["train", "val", "test"]:
    print(f"\n{split.upper()}:")
    for cls in ["book", "newspaper", "microfilm"]:
        p = root / split / cls
        count = len(list(p.glob("*"))) if p.exists() else 0
        print(cls, p.exists(), count)

from ultralytics import YOLO

model = YOLO("yolov8s-cls.pt")
model.train(
    data="/content/drive/MyDrive/classifier",
    imgsz=384,
    batch=32,
    epochs=80,
    patience=20,
    project="/content/drive/MyDrive/yolo_runs/classifier",
    name="doc_type_cls_rot_l4",
    device=0
)

from ultralytics import YOLO
best = YOLO("/content/drive/MyDrive/yolo_runs/classifier/doc_type_cls_rot_l4/weights/best.pt")

# Original test
best.val(data="/content/drive/MyDrive/classifier", split="test", imgsz=384, batch=32, device=0)

from pathlib import Path
from PIL import Image
import shutil

root = Path("/content/drive/MyDrive/classifier")
src_test = root / "test"
dst_test_rot = root / "test_rotated"

classes = ["book", "newspaper", "microfilm"]
exts = {".jpg", ".jpeg", ".png", ".tif", ".tiff", ".bmp", ".webp"}

# reset destination
if dst_test_rot.exists():
    shutil.rmtree(dst_test_rot)
dst_test_rot.mkdir(parents=True, exist_ok=True)

rot_ops = [
    ("rot0",   None),
    ("rot90",  Image.Transpose.ROTATE_270),  # 90 CW
    ("rot180", Image.Transpose.ROTATE_180),
    ("rot270", Image.Transpose.ROTATE_90),   # 270 CW
]

created = 0
for cls in classes:
    src_cls = src_test / cls
    dst_cls = dst_test_rot / cls
    dst_cls.mkdir(parents=True, exist_ok=True)

    for p in src_cls.iterdir():
        if p.suffix.lower() not in exts:
            continue
        with Image.open(p) as im:
            for tag, op in rot_ops:
                out = dst_cls / f"{p.stem}_{tag}{p.suffix}"
                if op is None:
                    im.save(out)  # copy original as rot0
                else:
                    im.transpose(op).save(out)
                created += 1

print("Created files in test_rotated:", created)
for cls in classes:
    print(cls, len(list((dst_test_rot / cls).glob("*"))))

from pathlib import Path
import shutil
from ultralytics import YOLO

root = Path("/content/drive/MyDrive/classifier")
tmp = Path("/content/classifier_eval_rot")

if tmp.exists():
    shutil.rmtree(tmp)
tmp.mkdir(parents=True, exist_ok=True)

# keep train/val from original, use test_rotated as test
shutil.copytree(root / "train", tmp / "train")
shutil.copytree(root / "val", tmp / "val")
shutil.copytree(root / "test_rotated", tmp / "test")

best = YOLO("/content/drive/MyDrive/yolo_runs/classifier/doc_type_cls_rot_l4/weights/best.pt")
metrics_rot = best.val(data=str(tmp), split="test", imgsz=384, batch=32, device=0)

print("Rotated test top1:", metrics_rot.top1)
print("Rotated test top5:", metrics_rot.top5)

from ultralytics import YOLO

model = YOLO("/content/drive/MyDrive/yolo_runs/classifier/doc_type_cls_rot_l4/weights/best.pt")

res = model.predict(
    source="/content/drive/MyDrive/imagee2.png",  # <-- your random image path
    imgsz=384,
    device=0,
    save=True,
    project="/content/drive/MyDrive/yolo_runs/classifier",
    name="random_one_pred",
)